/*
 * Copyright 2026 Jason Figge
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// chips-gates.js — the combinational-gate wave of the 74xx catalog: METADATA
// ONLY (identity, package, real pinouts); behavior lands in Feature 80. Pure
// data — no chip-specific code paths anywhere. The catalog integrity test
// validates every def (pin count matches the package, exactly one vcc + one
// gnd at the standard corners, unique pin numbers/names).
//
// Pin roles: input | output | vcc | gnd | nc.

/** Shorthand builders keep the defs readable; the data stays plain objects. */
const pin = (n, name, role) => ({ n, name, role });
const input = (n, name) => pin(n, name, "input");
const output = (n, name) => pin(n, name, "output");
const nc = (n) => pin(n, "NC", "nc");
const gnd = (n) => pin(n, "GND", "gnd");
const vcc = (n) => pin(n, "VCC", "vcc");

export const CHIPS_GATES = Object.freeze([
  {
    id: "7400",
    title: "Quad 2-input NAND",
    blurb: "Four independent 2-input NAND gates — the classic TTL workhorse.",
    group: "NAND",
    package: "DIP-14",
    pins: [
      input(1, "1A"),
      input(2, "1B"),
      output(3, "1Y"),
      input(4, "2A"),
      input(5, "2B"),
      output(6, "2Y"),
      gnd(7),
      output(8, "3Y"),
      input(9, "3A"),
      input(10, "3B"),
      output(11, "4Y"),
      input(12, "4A"),
      input(13, "4B"),
      vcc(14),
    ],
  },
  {
    id: "7402",
    title: "Quad 2-input NOR",
    blurb: "Four independent 2-input NOR gates (outputs on the low pins).",
    group: "NOR",
    package: "DIP-14",
    pins: [
      output(1, "1Y"),
      input(2, "1A"),
      input(3, "1B"),
      output(4, "2Y"),
      input(5, "2A"),
      input(6, "2B"),
      gnd(7),
      input(8, "3A"),
      input(9, "3B"),
      output(10, "3Y"),
      input(11, "4A"),
      input(12, "4B"),
      output(13, "4Y"),
      vcc(14),
    ],
  },
  {
    id: "7404",
    title: "Hex inverter",
    blurb: "Six independent NOT gates.",
    group: "Inverter",
    package: "DIP-14",
    pins: [
      input(1, "1A"),
      output(2, "1Y"),
      input(3, "2A"),
      output(4, "2Y"),
      input(5, "3A"),
      output(6, "3Y"),
      gnd(7),
      output(8, "4Y"),
      input(9, "4A"),
      output(10, "5Y"),
      input(11, "5A"),
      output(12, "6Y"),
      input(13, "6A"),
      vcc(14),
    ],
  },
  {
    id: "7408",
    title: "Quad 2-input AND",
    blurb: "Four independent 2-input AND gates.",
    group: "AND",
    package: "DIP-14",
    pins: [
      input(1, "1A"),
      input(2, "1B"),
      output(3, "1Y"),
      input(4, "2A"),
      input(5, "2B"),
      output(6, "2Y"),
      gnd(7),
      output(8, "3Y"),
      input(9, "3A"),
      input(10, "3B"),
      output(11, "4Y"),
      input(12, "4A"),
      input(13, "4B"),
      vcc(14),
    ],
  },
  {
    id: "7410",
    title: "Triple 3-input NAND",
    blurb: "Three independent 3-input NAND gates.",
    group: "NAND",
    package: "DIP-14",
    pins: [
      input(1, "1A"),
      input(2, "1B"),
      input(3, "2A"),
      input(4, "2B"),
      input(5, "2C"),
      output(6, "2Y"),
      gnd(7),
      output(8, "3Y"),
      input(9, "3A"),
      input(10, "3B"),
      input(11, "3C"),
      output(12, "1Y"),
      input(13, "1C"),
      vcc(14),
    ],
  },
  {
    id: "7411",
    title: "Triple 3-input AND",
    blurb: "Three independent 3-input AND gates.",
    group: "AND",
    package: "DIP-14",
    pins: [
      input(1, "1A"),
      input(2, "1B"),
      input(3, "2A"),
      input(4, "2B"),
      input(5, "2C"),
      output(6, "2Y"),
      gnd(7),
      output(8, "3Y"),
      input(9, "3A"),
      input(10, "3B"),
      input(11, "3C"),
      output(12, "1Y"),
      input(13, "1C"),
      vcc(14),
    ],
  },
  {
    id: "7420",
    title: "Dual 4-input NAND",
    blurb: "Two independent 4-input NAND gates.",
    group: "NAND",
    package: "DIP-14",
    pins: [
      input(1, "1A"),
      input(2, "1B"),
      nc(3),
      input(4, "1C"),
      input(5, "1D"),
      output(6, "1Y"),
      gnd(7),
      output(8, "2Y"),
      input(9, "2A"),
      input(10, "2B"),
      nc(11),
      input(12, "2C"),
      input(13, "2D"),
      vcc(14),
    ],
  },
  {
    id: "7427",
    title: "Triple 3-input NOR",
    blurb: "Three independent 3-input NOR gates.",
    group: "NOR",
    package: "DIP-14",
    pins: [
      input(1, "1A"),
      input(2, "1B"),
      input(3, "2A"),
      input(4, "2B"),
      input(5, "2C"),
      output(6, "2Y"),
      gnd(7),
      output(8, "3Y"),
      input(9, "3A"),
      input(10, "3B"),
      input(11, "3C"),
      output(12, "1Y"),
      input(13, "1C"),
      vcc(14),
    ],
  },
  {
    id: "7430",
    title: "8-input NAND",
    blurb: "A single 8-input NAND gate.",
    group: "NAND",
    package: "DIP-14",
    pins: [
      input(1, "A"),
      input(2, "B"),
      input(3, "C"),
      input(4, "D"),
      input(5, "E"),
      input(6, "F"),
      gnd(7),
      output(8, "Y"),
      nc(9),
      nc(10),
      input(11, "G"),
      input(12, "H"),
      nc(13),
      vcc(14),
    ],
  },
  {
    id: "7432",
    title: "Quad 2-input OR",
    blurb: "Four independent 2-input OR gates.",
    group: "OR",
    package: "DIP-14",
    pins: [
      input(1, "1A"),
      input(2, "1B"),
      output(3, "1Y"),
      input(4, "2A"),
      input(5, "2B"),
      output(6, "2Y"),
      gnd(7),
      output(8, "3Y"),
      input(9, "3A"),
      input(10, "3B"),
      output(11, "4Y"),
      input(12, "4A"),
      input(13, "4B"),
      vcc(14),
    ],
  },
  {
    id: "7486",
    title: "Quad 2-input XOR",
    blurb: "Four independent 2-input exclusive-OR gates.",
    group: "XOR",
    package: "DIP-14",
    pins: [
      input(1, "1A"),
      input(2, "1B"),
      output(3, "1Y"),
      input(4, "2A"),
      input(5, "2B"),
      output(6, "2Y"),
      gnd(7),
      output(8, "3Y"),
      input(9, "3A"),
      input(10, "3B"),
      output(11, "4Y"),
      input(12, "4A"),
      input(13, "4B"),
      vcc(14),
    ],
  },
  {
    id: "74125",
    title: "Quad bus buffer, tri-state",
    blurb:
      "Four independent buffers with active-low output-enable (tri-state).",
    group: "Buffer",
    package: "DIP-14",
    pins: [
      input(1, "1G"),
      input(2, "1A"),
      output(3, "1Y"),
      input(4, "2G"),
      input(5, "2A"),
      output(6, "2Y"),
      gnd(7),
      output(8, "3Y"),
      input(9, "3A"),
      input(10, "3G"),
      output(11, "4Y"),
      input(12, "4A"),
      input(13, "4G"),
      vcc(14),
    ],
  },
]);
