// ChipHippo.h — generated by Chip Hippo 1.0.2 for the connection "Arduino1".
//
//   Project:  6502
//   Desktop:  Desktop 3
//   Design:   0x91086DB3
//   Layout:   0xBB663BB4 (O0:1+1,I0:1+1+1+1)
//   Protocol: v1
//
// Do not edit this file: regenerate it from Chip Hippo (the Generate button)
// whenever this connection's Outputs or Inputs change. Your sketch includes it
// — from the .ino only — calls ChipHippo.begin() in setup() and
// ChipHippo.poll() in loop(), and defines one function per Output.
//
// Names read from the Arduino's side. An Output of the circuit ARRIVES
// here, so its function is its name + In, its fields the parameters; an
// Input of the circuit is SENT from here, as ChipHippo.<its name + Out>.
//
//   void Output3In(bool bit0, bool bit1) { … }  // the Output "Output 3"
//
// Set what changed, then send() the whole group as one value:
//
//   ChipHippo.DipsOut.setDip1(true);  // the Input "Dips"
//   ChipHippo.DipsOut.send();
//
// send() returns false while no run is listening (ChipHippo.connected()).
// An Input drives nothing until its first send(), so give each one its
// starting value from ChipHippo.onConnect(fn): poll() runs fn at the start
// of every run, whether or not the board reset when the port opened.
//
// ChipHippoExample.ino is an example sketch that uses this header — receiving,
// sending and logging: in Chip Hippo, Generate shows it beside this header.
//
// Call poll() often and keep Output functions short. While an Output is
// being handled the circuit waits for it, so every delay() is time the
// circuit stands still — Chip Hippo resends after 500 ms and stops the
// circuit after 3 tries. Log with ChipHippo.print()/println(), never
// Serial: Chip Hippo owns the port while the circuit runs.

#ifndef CHIPHIPPO_H
#define CHIPHIPPO_H

#include <Arduino.h>

#define CHIPHIPPO_PROTOCOL_VERSION 1
#define CHIPHIPPO_LAYOUT_SIGNATURE 0xBB663BB4UL
#define CHIPHIPPO_BAUD 115200UL
#define CHIPHIPPO_ACK_TIMEOUT_MS 500UL
#define CHIPHIPPO_MAX_SENDS 3

// ── Outputs: the circuit calls these. Implement each one in your sketch. ──
// Output 3: pin 1 bit0 (bool), pin 2 bit1 (bool)
void Output3In(bool bit0, bool bit1);

class ChipHippoLink;
extern ChipHippoLink ChipHippo;

// ── Inputs: set what changed, then send() the whole group as one frame. ──
// Dips: pin 1 Dip1 (bool), pin 2 Dip2 (bool), pin 3 Dip3 (bool), pin 4 Dip4 (bool)
class ChipHippo_DipsOut {
 public:
  void setDip1(bool on) { if (on) bits_ |= (uint16_t)(1u << 0); else bits_ &= (uint16_t)~(uint16_t)(1u << 0); }
  void setDip2(bool on) { if (on) bits_ |= (uint16_t)(1u << 1); else bits_ &= (uint16_t)~(uint16_t)(1u << 1); }
  void setDip3(bool on) { if (on) bits_ |= (uint16_t)(1u << 2); else bits_ &= (uint16_t)~(uint16_t)(1u << 2); }
  void setDip4(bool on) { if (on) bits_ |= (uint16_t)(1u << 3); else bits_ &= (uint16_t)~(uint16_t)(1u << 3); }
  // Send the whole group. True once Chip Hippo has it; false if it is not
  // listening (the circuit is not running, or the cable is out).
  bool send();
  uint16_t bits() const { return bits_; }

 private:
  uint16_t bits_ = 0;
};

class ChipHippoLink : public Print {
 public:
  ChipHippo_DipsOut DipsOut;

  // Open the serial port and announce the sketch. Call once, from setup().
  void begin(unsigned long baud = CHIPHIPPO_BAUD) {
    Serial.begin(baud);
    begin(Serial);
  }

  // The same, over a port you have already begun.
  void begin(Stream& io) {
    io_ = &io;
    inFrame_ = false;
    esc_ = false;
    rxLen_ = 0;
    greeted_ = false;
    session_ = 0;
    txSeq_ = 0;
    rxSeq_ = 0;
    dispatching_ = false;
    pending_ = false;
    connectPending_ = false;
    logLen_ = 0;
    // Session 0 says "I have just started": a circuit that was running
    // learns this sketch has forgotten it, and stops rather than go deaf.
    sendHelloAck(0, 0);
  }

  // Service the link: runs Output functions, answers Chip Hippo. Call it
  // from loop(), as often as you can.
  void poll() {
    if (!io_) return;
    pump(false, 0);
    if (connectPending_ && !dispatching_) {
      connectPending_ = false;
      if (onConnect_) onConnect_();
    }
    if (pending_ && !dispatching_) {
      pending_ = false;
      dispatch(pendingIndex_, pendingSeq_, pendingWidth_, pendingValue_);
    }
    flushLog(false);
  }

  // True from Chip Hippo's HELLO (for this design) until a send it never
  // acknowledged: while it is false, an Input's send() fails at once.
  bool connected() const { return greeted_; }

  // Run `fn` from poll() at the start of every run, once Chip Hippo has
  // greeted the sketch — whether or not the board reset when the port
  // opened (connected() alone cannot say so: between two runs it stays
  // true until a send fails). The place to send your Inputs' starting
  // values. Call it from setup(); 0 turns it off.
  void onConnect(void (*fn)()) { onConnect_ = fn; }

  // Log text: ChipHippo.print()/println() reach Chip Hippo's log window.
  size_t write(uint8_t b) {
    if (!io_) return 0;
    if (logLen_ == LOG_CHUNK) {
      flushLog(false);
      if (logLen_ == LOG_CHUNK) flushLog(true);  // no character to cut at
    }
    log_[logLen_++] = b;
    if (b == '\n') flushLog(true);
    return 1;
  }
  using Print::write;

  // Used by the Inputs' send(). Waits for Chip Hippo's ACK, resending on
  // a NAK or a timeout, and keeps the link serviced while it waits.
  bool sendInput(uint8_t index, uint8_t width, uint16_t value) {
    // Not in a session — or inside a handler whose session has ended.
    if (!io_ || !greeted_ || (dispatching_ && !busySeq_)) return false;
    flushLog(false);
    const uint8_t payload[DATA_LEN] = {index, width, (uint8_t)(value & 0xFF),
                                       (uint8_t)(value >> 8)};
    txSeq_ = (uint8_t)(txSeq_ % 255 + 1);
    const uint8_t seq = txSeq_;
    for (uint8_t n = 0; n < CHIPHIPPO_MAX_SENDS; n++) {
      sendFrame(F_INBOUND, seq, payload, DATA_LEN);
      unsigned long start = millis();
      while ((unsigned long)(millis() - start) < CHIPHIPPO_ACK_TIMEOUT_MS) {
        uint8_t r = pump(true, seq);
        if (txSeq_ != seq) return false;  // a new session reset txSeq_
        if (r == R_ACK) return true;
        if (r == R_NAK) break;
      }
    }
    // Nobody is listening: leave the session — nothing more of it goes out,
    // not even a held or running Output's ACK — and say so, as begin() does.
    greeted_ = false;
    busySeq_ = 0;
    pending_ = false;
    sendHelloAck(0, 0);
    return false;
  }

 private:
  enum { K_START = 0x7E, K_ESC = 0x7D, K_ESC_XOR = 0x20 };
  enum { F_HELLO = 0x01, F_HELLO_ACK = 0x02, F_ACK = 0x06, F_NAK = 0x15,
         F_OUTPUT = 0x10, F_INBOUND = 0x11, F_LOG = 0x20 };
  enum { R_NONE = 0, R_ACK = 1, R_NAK = 2 };
  enum { HEADER = 3, CRC_LEN = 2, DATA_LEN = 4, HELLO_LEN = 7, HELLO_MIN = 3 };
  // The longest frame this side is ever sent: anything longer is damage.
  enum { RX_MAX = 7, LOG_CHUNK = 60 };
  enum { OUTPUT_COUNT = 1, INPUT_COUNT = 1 };

  // CRC-16/CCITT-FALSE, a bit at a time: no table, so no flash spent on one.
  static uint16_t crcStep(uint16_t crc, uint8_t b) {
    crc ^= (uint16_t)((uint16_t)b << 8);
    for (uint8_t i = 0; i < 8; i++) {
      crc = (crc & 0x8000) ? (uint16_t)((crc << 1) ^ 0x1021) : (uint16_t)(crc << 1);
    }
    return crc;
  }

  static uint16_t crc16(const uint8_t* p, uint8_t n) {
    uint16_t crc = 0xFFFF;
    while (n--) crc = crcStep(crc, *p++);
    return crc;
  }

  void putEscaped(uint8_t b) {
    if (b == K_START || b == K_ESC) {
      io_->write((uint8_t)K_ESC);
      io_->write((uint8_t)(b ^ K_ESC_XOR));
    } else {
      io_->write(b);
    }
  }

  void sendFrame(uint8_t type, uint8_t seq, const uint8_t* payload,
                 uint8_t len) {
    uint16_t crc = 0xFFFF;
    io_->write((uint8_t)K_START);
    const uint8_t head[HEADER] = {type, seq, len};
    for (uint8_t i = 0; i < HEADER; i++) {
      crc = crcStep(crc, head[i]);
      putEscaped(head[i]);
    }
    for (uint8_t i = 0; i < len; i++) {
      crc = crcStep(crc, payload[i]);
      putEscaped(payload[i]);
    }
    putEscaped((uint8_t)(crc & 0xFF));
    putEscaped((uint8_t)(crc >> 8));
  }

  // An Output's ACK: its SEQ is the one a resend is recognised by.
  void ack(uint8_t seq) {
    rxSeq_ = seq;
    sendFrame(F_ACK, seq, 0, 0);
  }

  // This sketch's version, `session` and layout, to any HELLO: only Chip
  // Hippo judges. True if the HELLO in rx_ was these 7 bytes: joinable.
  bool sendHelloAck(uint16_t session, uint8_t len) {
    const unsigned long s = CHIPHIPPO_LAYOUT_SIGNATURE;
    const uint8_t p[HELLO_LEN] = {
        CHIPHIPPO_PROTOCOL_VERSION,  (uint8_t)(session & 0xFF),
        (uint8_t)(session >> 8),     (uint8_t)(s & 0xFF),
        (uint8_t)((s >> 8) & 0xFF),  (uint8_t)((s >> 16) & 0xFF),
        (uint8_t)((s >> 24) & 0xFF)};
    sendFrame(F_HELLO_ACK, 0, p, HELLO_LEN);
    uint8_t i = 0;
    while (i < HELLO_LEN && rx_[HEADER + i] == p[i]) i++;
    return len == HELLO_LEN && i == HELLO_LEN;
  }

  // How much of the log ends on a whole UTF-8 character: a LOG frame never
  // splits one.
  uint8_t wholeChars() const {
    uint8_t i = logLen_, tail = 0;
    while (i > 0 && tail < 3 && (log_[i - 1] & 0xC0) == 0x80) {
      i--;
      tail++;
    }
    if (i == 0) return logLen_;
    const uint8_t lead = log_[i - 1];
    const uint8_t need = lead >= 0xF0 ? 4 : lead >= 0xE0 ? 3 : lead >= 0xC0 ? 2 : 1;
    return need > tail + 1 ? (uint8_t)(i - 1) : logLen_;
  }

  // Send what the log holds (up to its last whole character, unless `all`).
  // Log text is never acknowledged, so it goes whether or not anyone is
  // listening — and never keeps the sketch waiting.
  void flushLog(bool all) {
    if (!io_ || logLen_ == 0) return;
    const uint8_t n = all ? logLen_ : wholeChars();
    if (n == 0) return;
    sendFrame(F_LOG, 0, log_, n);
    for (uint8_t i = n; i < logLen_; i++) log_[i - n] = log_[i];
    logLen_ = (uint8_t)(logLen_ - n);
  }

  // Read what has arrived. Returns R_ACK/R_NAK when `waiting` and the frame
  // it waits on was answered; frames for someone else are handled here.
  uint8_t pump(bool waiting, uint8_t waitSeq) {
    while (io_->available() > 0) {
      uint8_t b = (uint8_t)io_->read();
      if (b == K_START) {
        inFrame_ = true;
        esc_ = false;
        rxLen_ = 0;
        continue;
      }
      if (!inFrame_) continue;
      if (esc_) {
        esc_ = false;
        b ^= K_ESC_XOR;
        if (b != K_START && b != K_ESC) {
          damaged();
          continue;
        }
      } else if (b == K_ESC) {
        esc_ = true;
        continue;
      }
      rx_[rxLen_++] = b;
      if (rxLen_ < HEADER) continue;
      const uint8_t len = rx_[2];
      if (len > RX_MAX) {
        damaged();
        continue;
      }
      if (rxLen_ < (uint8_t)(HEADER + len + CRC_LEN)) continue;
      inFrame_ = false;
      uint8_t r = handle(len, waiting, waitSeq);
      if (waiting && r != R_NONE) return r;
    }
    return R_NONE;
  }

  // A frame arrived damaged: ask for a resend at once — unless it was one
  // that is never resent, or this sketch is in no session.
  void damaged() {
    inFrame_ = false;
    const uint8_t type = rxLen_ ? rx_[0] : 0;
    if (greeted_ && type != F_HELLO && type != F_HELLO_ACK && type != F_ACK && type != F_NAK && type != F_LOG) {
      sendFrame(F_NAK, 0, 0, 0);
    }
  }

  uint8_t handle(uint8_t len, bool waiting, uint8_t waitSeq) {
    const uint8_t type = rx_[0], seq = rx_[1];
    const uint16_t crc =
        (uint16_t)(rx_[HEADER + len] | ((uint16_t)rx_[HEADER + len + 1] << 8));
    if (crc16(rx_, (uint8_t)(HEADER + len)) != crc) {
      damaged();
      return R_NONE;
    }
    if (type == F_HELLO) {
      onHello(len);
      return R_NONE;
    }
    if (!greeted_) return R_NONE;  // nothing counts before a HELLO
    switch (type) {
      case F_ACK:
        return (waiting && seq == waitSeq) ? R_ACK : R_NONE;
      case F_NAK:
        return waiting ? R_NAK : R_NONE;
      case F_OUTPUT:
        if (!seq) return R_NONE;  // SEQ 0 is never a data frame's
        // Intact but unreadable: ACK and drop — a resend would be the same.
        if (len == DATA_LEN) onOutput(seq, waiting);
        else ack(seq);
        return R_NONE;
      default:
        return R_NONE;
    }
  }

  // A HELLO names the run's SESSION (never 0). Only a new one resets what
  // this side remembers — a repeat of the last (the host asks until it
  // hears) is answered and nothing more, or it would rewind the SEQs.
  void onHello(uint8_t len) {
    const uint16_t session =
        (uint16_t)(rx_[HEADER + 1] | ((uint16_t)rx_[HEADER + 2] << 8));
    if (len < HELLO_MIN || session == 0) return;
    const bool join = sendHelloAck(session, len);
    if (session == session_) return;
    session_ = session;
    greeted_ = join;
    connectPending_ = join;  // a new run: poll() runs onConnect
    txSeq_ = 0;
    rxSeq_ = 0;
    busySeq_ = 0;  // an Output being handled is the old run's: no ACK
    pending_ = false;
  }

  void onOutput(uint8_t seq, bool waiting) {
    // A resend of one already handled: its ACK was lost. ACK, act once.
    if (seq == rxSeq_) {
      ack(seq);
      return;
    }
    // A resend of the one being handled, or held, right now: its ACK
    // follows when the handler returns — an ACK now would let the circuit
    // run on before the handler's own Inputs had reached it.
    if (dispatching_ && seq == busySeq_) return;
    if (pending_ && seq == pendingSeq_) return;
    const uint8_t index = rx_[HEADER], width = rx_[HEADER + 1];
    const uint16_t value =
        (uint16_t)(rx_[HEADER + 2] | ((uint16_t)rx_[HEADER + 3] << 8));
    if (waiting || dispatching_) {
      // Never run a handler inside send() or inside another handler: hold
      // it for poll(). Chip Hippo sends one Output at a time, so one slot.
      pending_ = true;
      pendingIndex_ = index;
      pendingSeq_ = seq;
      pendingWidth_ = width;
      pendingValue_ = value;
      return;
    }
    dispatch(index, seq, width, value);
  }

  // Run an Output's function, then ACK — so Chip Hippo, which waits for
  // the ACK, knows the sketch has acted on it, and has everything the
  // function sent (its Inputs, its log) ahead of it.
  void dispatch(uint8_t index, uint8_t seq, uint8_t width, uint16_t v) {
    dispatching_ = true;
    busySeq_ = seq;
    switch (index) {
      case 0:
        if (width == 2) Output3In(((v & 1u) != 0), (((v >> 1) & 1u) != 0));
        break;
      default:
        (void)v;
        (void)width;
        break;
    }
    dispatching_ = false;
    if (busySeq_ != seq) return;  // a new session began meanwhile
    flushLog(false);
    ack(seq);
  }

  Stream* io_ = 0;
  uint8_t rx_[HEADER + RX_MAX + CRC_LEN];
  uint8_t rxLen_ = 0;
  bool inFrame_ = false;
  bool esc_ = false;
  bool greeted_ = false;
  uint16_t session_ = 0;
  uint8_t txSeq_ = 0;
  uint8_t rxSeq_ = 0;
  bool dispatching_ = false;
  uint8_t busySeq_ = 0;
  bool pending_ = false;
  uint8_t pendingIndex_ = 0, pendingSeq_ = 0, pendingWidth_ = 0;
  uint16_t pendingValue_ = 0;
  uint8_t log_[LOG_CHUNK];
  uint8_t logLen_ = 0;
  void (*onConnect_)() = 0;
  bool connectPending_ = false;
};

inline bool ChipHippo_DipsOut::send() { return ChipHippo.sendInput(0, 4, bits_); }

// The one link. Defined here, so include this header from the .ino only.
ChipHippoLink ChipHippo;

#endif  // CHIPHIPPO_H
